"""add unique constraint to nickname

Revision ID: 792093520364
Revises: d45d116d0880
Create Date: 2026-05-14 21:59:14.773558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792093520364'
down_revision = 'd45d116d0880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_nickname', ['nickname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_nickname', type_='unique')

    # ### end Alembic commands ###
